services:
  app:
    image: {{ cookiecutter.project_slug }}-image
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - {{ cookiecutter.project_slug }}-net
  
  db:
    image: postgres:17.5-bookworm
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - {{ cookiecutter.project_slug }}-net

volumes:
  postgres_data:

networks:
  {{ cookiecutter.project_slug }}-net:
    driver: bridge
